base_url = "https://isunjn.me"
title = "isunjn"
description = "Personal website of @isunjn"
default_language = "zh-CN"
theme = "serene"
output_dir = "docs"
compile_sass = true
minify_html = true
build_search_index = false
generate_feed = false
feed_filename = "atom.xml"
taxonomies = [
    {name = "tags"},
    {name = "categories"}
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"
render_emoji = true

[search]
include_title = true
include_description = false
include_path = false
include_content = true

[extra]
name = "Jianan Sun"
id = "isunjn"
bio = "In programming we trust"
avatar = "img/avatar.png"

show_id = true
show_projects = false #TODO
blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"

links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/isunjn"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/isunjn"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:isunjn@gmail.com"},
    {name = "GPG", icon = "ri-fingerprint-line", url = "https://github.com/isunjn.gpg"},
]

toc = true
blur_effect = true
back_to_top_button = true
progress_bar = true
author_info_under_post = false # TODO
cc_license = true
cc_license_info = "本文采用 [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/) 进行许可，如需转载，请联系作者"

outdate_warn = false
outdate_warn_days = 120
outdate_warn_text1 = "注意，本文最后更新于 "
outdate_warn_text2 = " 天前，部分内容可能已失去时效性，请谨慎参考"

footer_copyright_name = "isunjn"
footer_copyright_year = "2021"
footer_credits = true

comment = "gitalk"
analytics = "umami"

# comment

[extra.gitalk]
client_id = "6af0871db49c6e53f977"
client_secret = "60616bbb966a81c6e997e04c3217318ecad9575e"
repo = "isunjn.github.io"
owner = "isunjn"
admin = ["isunjn"]
distraction_freeMode = false
per_page = 10
page_direction = "first"
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"

# analytics

[extra.umami]
website_id = "de3a268e-a2d2-4af6-8bfa-46cd6ca13e0d"
src = "https://umami-isunjn.vercel.app/umami.js"