base_url = "https://isunjn.me"
title = "isunjn"
description = "Personal website of @isunjn"
default_language = "zh-CN"
theme = "serene"
output_dir = "docs"
compile_sass = true
minify_html = false
build_search_index = false
generate_feed = false
feed_filename = "feed.xml"
taxonomies = [
    {name = "tags"},
    {name = "categories"}
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
name = "Jianan Sun"
id = "isunjn"
bio = "In programming we trust"
avatar = "img/avatar.webp"

show_id = true
show_projects = false

blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"
home_icon = "ri-user-6-line"
rss_icon = "ri-rss-line"
toc_icon = "ri-menu-2-line"

links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/isunjn"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/isunjn"},
    {name = "Telegram", icon = "ri-send-plane-line", url = "https://t.me/isunjn"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:isunjn@gmail.com"},
    {name = "GPG", icon = "ri-fingerprint-line", url = "https://github.com/isunjn.gpg"},
]

feed_in_blog_section = true

toc = true
blur_effect = true
back_to_top_button = true
progress_bar = true
cc_license = true
cc_license_statement = "文章采用 [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/) 进行许可，未经允许禁止转载"
outdate_warn = false
outdate_warn_days = 120
outdate_warn_text1 = "注意：本文最后更新于 "
outdate_warn_text2 = " 天前，部分内容可能已失去时效性，请谨慎参考"

footer_copyright_name = "isunjn"
footer_copyright_year = "2022"
# footer_custom = "xxxxxxxx"
footer_credits = true

comment = "gitalk"
analytics = "umami"

#======================= Comment =======================

[extra.gitalk]
client_id = "6af0871db49c6e53f977"
client_secret = "60616bbb966a81c6e997e04c3217318ecad9575e"
repo = "isunjn.github.io"
owner = "isunjn"
admin = ["isunjn"]
distraction_free_mode = false
per_page = 10
page_direction = "first"
proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"

[extra.disqus]
shortname = "isunjn-1"

#======================= Analytics =======================

[extra.umami]
website_id = "de3a268e-a2d2-4af6-8bfa-46cd6ca13e0d"
src = "https://umami-isunjn.vercel.app/umami.js"